# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: git config --global user.email "you@example.com" && git config --global user.name "Your Name" && mkdir ~/build && mkdir ~/build/bin && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/build/bin/repo && chmod a+x ~/build/bin/repo && export PATH=~/build/bin:$PATH && repo init -u https://android.googlesource.com/platform/manifest -b android-1.6_r1_ && repo sync -c --no-clone-bundle --no-tags -j2 && source build/envsetup.sh && lunch generic-eng
      - store_artifacts:
          path: example.txt
workflows:
  example:
    jobs:
      - build
