# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    resource_class: small
    steps:
      # Replace this with steps to build a package, or executable
      - run:
        name: Dependencies
        command: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
workflows:
  example:
    jobs:
    - build
